// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("ReggerIt")>]
[<assembly: AssemblyProductAttribute("ReggerIt")>]
[<assembly: AssemblyVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2021-03-20T00:00:00.0000000+01:00")>]
[<assembly: AssemblyFileVersionAttribute("0.1.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","8a6fe5fa2499a86829bf2d95f693f832dd850a83")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "ReggerIt"
    let [<Literal>] AssemblyProduct = "ReggerIt"
    let [<Literal>] AssemblyVersion = "0.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2021-03-20T00:00:00.0000000+01:00"
    let [<Literal>] AssemblyFileVersion = "0.1.0"
    let [<Literal>] AssemblyInformationalVersion = "0.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "8a6fe5fa2499a86829bf2d95f693f832dd850a83"
